name: "sample"
replicaCount: 1

ingressController: nginx

service:
  type: ClusterIP

domainName: "daric.vc"

tls:
  enabled: false
  clusterIssuer: cf-letsencrypt
  secretName: daric-vc-wildcard-tls

image:
  repository: "briofy.{{ .Values.name }}-web"
  pullPolicy: Always
  tag: latest

resources: {}
tolerations: {}
